machine_list = [
    { name = "theia221", machine_ip = "theia221.dcc.fc.up.pt" },
    { name = "theia222", machine_ip = "theia222.dcc.fc.up.pt" },
    { name = "theia223", machine_ip = "theia223.dcc.fc.up.pt" },
    { name = "theia224", machine_ip = "theia224.dcc.fc.up.pt" },
    { name = "theia225", machine_ip = "theia225.dcc.fc.up.pt" },
    { name = "theia226", machine_ip = "theia226.dcc.fc.up.pt" },
    { name = "theia227", machine_ip = "theia227.dcc.fc.up.pt" },
]