#!/bin/sh

CA_ROOT=ca-root
DAYS=999999

CLI_AMT=1000
SRV_AMT=13

CLI_PREFIX=cli
SRV_PREFIX=cop

updatecwd() {
    cd "$(dirname $0)"
}

regenerate() {
    echo Removing old CA
    rm -rf $CA_ROOT
    mkdir $CA_ROOT

    echo Generating new root key
    openssl genrsa -out $CA_ROOT/root.key 2048

    echo Generating new root certificate
    openssl req -new -x509 -subj "/CN=localhost" -sha256 -key $CA_ROOT/root.key -nodes \
        -days $DAYS -out $CA_ROOT/root.crt
}

main() {
    updatecwd
    regenerate
}

main
