bootstrap_nodes = [
    { node_id = 0, ip = "replica-0", port = 10000, hostname = "srv0", node_type = "Replica" },
    { node_id = 1, ip = "replica-1", port = 10000, hostname = "srv1", node_type = "Replica" },
    { node_id = 2, ip = "replica-2", port = 10000, hostname = "srv2", node_type = "Replica" },
    { node_id = 3, ip = "replica-3", port = 10000, hostname = "srv3", node_type = "Replica" },
]

[own_node]
#node_id = 0
#ip = ""
port = 10000
#hostname = "srv0"
#node_type = "Replica"
