#!/bin/sh

main() {
    regen_config_folder "$1"

    cd $1/config || exit 0

    #regen_hosts_file
}

regen_config_folder() {
    rm -rf $1/config
    cp -r config $1/config
}

regen_hosts_file() {
    rm -f hosts.config
    for id in `seq 0 $(expr $NUM_REPLICAS - 1)`; do
        host=$(expr $id % 4)
        host=$(expr 24 + $host)
        port_1=$(expr 11000 + $(expr $id \* 10))
        port_2=$(expr $(expr 11000 + $(expr $id \* 10)) + 1)
        echo $id 192.168.85.$host $port_1 $port_2 >> hosts.config
    done
}

main "$@"
