#!/bin/sh

cleanup() {
    pkill cargo
    pkill consensus
}

# cleanup at exit
trap 'cleanup' EXIT INT

# update env
export RUSTFLAGS='-C target-cpu=native'
export PATH="$HOME/.cargo/bin:$PATH"

# change dir
cd $HOME/tg/consensus

# update code
git pull

# build code
cargo build --release || exit 1

# run code
./target/release/consensus
