#!/usr/bin/env bash
# gen-grafana.sh
#
# Resolves the InfluxDB instance the benchmark writes to and generates everything the
# metrics stack needs to agree with it:
#
#   generated/grafana/influxdb.env              InfluxDB *server* env (LOCAL_INFLUXDB=1)
#   generated/grafana/grafana.env               INFLUX_URL/DB/USER/PASSWORD
#   generated/grafana/datasources/influxdb.yml  provisioned datasource (uid atlas-influx)
#
# The point of generating these rather than checking them in: there is exactly one
# source of truth for where metrics go — config-base/common/influx_db.toml, the same
# file the replicas and clients read — and LOCAL_INFLUXDB flips that target to an
# in-network container. Three parties have to agree on it:
#
#   the writers  replicas/clients, from generated/config-*/influx_db.toml
#   the server   the influxdb container, from influxdb.env (db name + admin user)
#   the reader   Grafana, from grafana.env + the provisioned datasource
#
# Deriving all three here is what stops a run writing to a database Grafana is not
# reading, or a server that never created the database the writers name.
#
# Environment (exported by the shared bench Makefile):
#   GLOBAL_BENCH_DIR      - absolute path to testing-grounds/bench
#   GENERATED             - absolute path to the shared generated/ dir
#   LOCAL_INFLUXDB        - 1 if the metrics stack runs its own InfluxDB container
#   INFLUXDB_AUTH_ENABLED - HTTP auth on the local container (default false)
#
# Optional overrides (bench.env); each falls back to the resolved value when empty:
#   GRAFANA_INFLUX_URL, GRAFANA_INFLUX_DB, GRAFANA_INFLUX_USER, GRAFANA_INFLUX_PASSWORD

set -euo pipefail

: "${GLOBAL_BENCH_DIR:?GLOBAL_BENCH_DIR not set}"
: "${GENERATED:?GENERATED not set}"
: "${LOCAL_INFLUXDB:=1}"
: "${INFLUXDB_AUTH_ENABLED:=false}"

INFLUX_TOML="$GLOBAL_BENCH_DIR/config-base/common/influx_db.toml"
OUT_DIR="$GENERATED/grafana"

# Value of a `key = "value"` line in the influx TOML. Takes the text between the
# first and last double quote on the line, so passwords containing #, $ or % (the
# checked-in one contains all three) survive intact.
toml_get() {
    [ -f "$INFLUX_TOML" ] || return 0
    sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\"\(.*\)\"[[:space:]]*$/\1/p" \
        "$INFLUX_TOML" | head -n 1
}

TOML_IP="$(toml_get ip)"
TOML_DB="$(toml_get db_name)"
TOML_USER="$(toml_get user)"
TOML_PASSWORD="$(toml_get password)"

if [ "$LOCAL_INFLUXDB" = "1" ]; then
    # The metrics stack brings up an InfluxDB container on atlas_network under the
    # `influxdb` alias; gen-local-compose.sh rewrites the generated replica/client
    # configs to that address. Only the *address* is overridden — the database name
    # still comes from the TOML, and influxdb.env below makes the server create
    # exactly that one, so all three parties stay on the same database.
    RESOLVED_URL="http://influxdb:8086"
    RESOLVED_DB="$TOML_DB"
    SOURCE_NOTE="LOCAL_INFLUXDB=1 — in-network InfluxDB container on atlas_network"
else
    RESOLVED_URL="$TOML_IP"
    RESOLVED_DB="$TOML_DB"
    SOURCE_NOTE="external InfluxDB from config-base/common/influx_db.toml"
fi

# Credentials always come from the TOML: harmless when the local container has auth
# disabled, and correct the moment it is enabled or the target is external.
URL="${GRAFANA_INFLUX_URL:-$RESOLVED_URL}"
DB="${GRAFANA_INFLUX_DB:-$RESOLVED_DB}"
USER="${GRAFANA_INFLUX_USER:-$TOML_USER}"
PASSWORD="${GRAFANA_INFLUX_PASSWORD:-$TOML_PASSWORD}"

if [ -z "$URL" ] || [ -z "$DB" ]; then
    echo "ERROR: could not resolve an InfluxDB target for Grafana." >&2
    echo "       Checked $INFLUX_TOML (ip / db_name)." >&2
    echo "       Set GRAFANA_INFLUX_URL and GRAFANA_INFLUX_DB in bench.env to override." >&2
    exit 1
fi

mkdir -p "$OUT_DIR/datasources"

# Single-quoted so neither Compose nor podman-compose interpolates a '$' inside a
# password. An embedded single quote is escaped the POSIX way ('\'').
env_line() {
    printf "%s='%s'\n" "$1" "$(printf '%s' "$2" | sed "s/'/'\\\\''/g")"
}

{
    echo "# Generated by gen-grafana.sh — do not edit by hand."
    echo "# Source: $SOURCE_NOTE"
    env_line INFLUX_URL "$URL"
    env_line INFLUX_DB "$DB"
    env_line INFLUX_USER "$USER"
    env_line INFLUX_PASSWORD "$PASSWORD"
} > "$OUT_DIR/grafana.env"

# ── InfluxDB server env ───────────────────────────────────────────────────────────
# Consumed by the influxdb service's env_file. INFLUXDB_DB and INFLUXDB_ADMIN_USER
# make the 1.8 entrypoint create the database and the admin user on the volume's first
# initialisation; both are no-ops on an already-initialised volume, which is why
# metrics-up.sh also issues CREATE DATABASE against a running server.
#
# The admin user is created whether or not auth is on, so INFLUXDB_AUTH_ENABLED can be
# flipped to true later without recreating the volume. Written unconditionally: the
# file is cheap, and Compose fails to even parse the stack when a declared env_file is
# missing — including with LOCAL_INFLUXDB=0, where the service is merely filtered out
# by its profile.
{
    echo "# Generated by gen-grafana.sh — do not edit by hand."
    echo "# Source: $GLOBAL_BENCH_DIR/config-base/common/influx_db.toml"
    env_line INFLUXDB_DB "$DB"
    env_line INFLUXDB_ADMIN_USER "$USER"
    env_line INFLUXDB_ADMIN_PASSWORD "$PASSWORD"
    env_line INFLUXDB_HTTP_AUTH_ENABLED "$INFLUXDB_AUTH_ENABLED"
} > "$OUT_DIR/influxdb.env"

# The datasource references the env vars rather than inlining the values: Grafana
# expands $VAR in provisioning files, so an inlined password containing '$' would be
# silently truncated.
cat > "$OUT_DIR/datasources/influxdb.yml" <<'YAML'
# Generated by gen-grafana.sh — do not edit by hand.
# Values come from the container environment (../grafana.env), which is derived from
# bench/config-base/common/influx_db.toml + LOCAL_INFLUXDB.
apiVersion: 1

datasources:
  - name: Atlas InfluxDB
    uid: atlas-influx
    type: influxdb
    access: proxy
    url: $INFLUX_URL
    database: $INFLUX_DB
    user: $INFLUX_USER
    isDefault: true
    editable: false
    jsonData:
      version: InfluxQL
      httpMode: GET
      # Atlas' metrics thread writes one point per metric per second.
      timeInterval: 1s
    secureJsonData:
      password: $INFLUX_PASSWORD
YAML

echo "Written $OUT_DIR/{influxdb.env,grafana.env,datasources/influxdb.yml}"
echo "  InfluxDB target: $URL (db '$DB', user '${USER:-<none>}') — $SOURCE_NOTE"
