- hosts: all
  become: true
  vars:
    working_dir: "/home/{{ ansible_user }}/atlas-microbenchmarks"
    replica_docker_file: "docker-compose-replica.yml"
    client_docker_file: "docker-compose-client.yml"
    replica_docker_files: "{{ working_dir }}/{{replica_docker_file}}"
    client_docker_files: "{{ working_dir }}/{{client_docker_file}}"
  tasks:
    - name: Start replicas detached
      shell: "docker compose -f \"{{replica_docker_file}}\" up -d"
      args:
        chdir: "{{ working_dir }}"
      ignore_errors: yes
    # We start the clients attached since they
    - name: Start clients attached
      shell: "docker compose -f \"{{client_docker_file}}\" up"
      args:
        chdir: "{{ working_dir }}"
      ignore_errors: yes