- hosts: all
  become: yes
  vars:
    clients:
      - 100
      - 200
      - 400
      - 800
    replicas:
      - 4
      - 8
      - 16
      - 32
    request_size:
      - 0
      - 128
      - 1024
      - 4096
    test-runs: 10
  tasks:
    - name: Generate docker compose files
      local_action:
        module: shell
        cmd: cargo run -- --replica-count {{replicas}} --client-count {{clients}} --request_size {{request_size}} --reply-size {{request_size}} round-robin
      args:
        chdir: ansible-compose-generation