worker_count = 4

[tcp_conns]
replica_concurrent_connections = 4
client_concurrent_connections = 1

[pool_config]
batch_limit = 1024
per_client_bound = 128
clients_per_pool = 1000
batch_timeout_micros = 100
batch_sleep_micros = 100
channel_size = 128
