#!/bin/sh

mkdir -p config
cd config

echo $BATCH_SIZE > batch.config

rm -f clients.config
#10gbe
#CLIENT_MACHINES="10.11.12.5"

#1gbe
CLIENT_MACHINES="192.168.85.30"

CURR_MACHINE=0
for ip in $CLIENT_MACHINES; do
  for i in $(seq 0 $(expr $NUM_CLIENTS - 1)); do
      id=$(expr 1000 + $(expr $(expr $CURR_MACHINE \* $NUM_CLIENTS) + $i))
      sni=cli${id}
      port=$(expr 11000 + $i)
      echo $id $sni $ip $port >> clients.config
  done

  CURR_MACHINE=$(expr $CURR_MACHINE + 1)
done

rm -f replicas.config
for id in `seq 0 $(expr $NUM_REPLICAS - 1)`; do
    sni=srv${id}
    port=$(expr 10000 + $id)
    rep_port=$(expr 12000 + $id)
    host=$(expr $id % 4)

    #1gbe
    host=$(expr 24 + $host)
    Gecho $id $sni 192.168.85.$host $port $rep_port >> replicas.config

    #10gbe
    #host=$(expr 1 + $host)
    #echo $id $sni 10.11.12.$host $port $rep_port >> replicas.config
done
