#!/bin/bash

main() {
    compile
    exec_microbenchmarks
}

compile() {
    [ "$COMPILE" -eq 1 ] && ./compile
}

exec_microbenchmarks() {
  exec ./target/release/microbenchmarks-async
}

main
#sudo apt install linux-tools-5.15 && echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
