#!/bin/sh

USER=tcarvalho
HOST=ssh.dcc.fc.up.pt

N1=34016
N2=34017
N3=34018
N4=34019

TEST_CASE=$1
DATA_SIZE=$2
BACKEND=$3

run() {
    ssh $USER@$HOST $@
}

case $TEST_CASE in
    update)
        run -t -p $N1 ". .cargo/env && cd ./tg/transport/ && git pull && env BUFSIZ=$DATA_SIZE cargo build --release"
        run -t -p $N2 ". .cargo/env && cd ./tg/transport/ && git pull && env BUFSIZ=$DATA_SIZE cargo build --release"
        run -t -p $N3 ". .cargo/env && cd ./tg/transport/ && git pull && env BUFSIZ=$DATA_SIZE cargo build --release"
        run -t -p $N4 ". .cargo/env && cd ./tg/transport/ && git pull && env BUFSIZ=$DATA_SIZE cargo build --release"
        ;;
    1)
        echo Not implemented yet...
        ;;
    2)
        run -p $N2 env THREADS=40 TEST=2 \
            ./tg/transport/target/release/transport ${BACKEND}:server &
        sleep 1
        run -p $N3 env THREADS=40 TEST=2 \
            ./tg/transport/target/release/transport ${BACKEND}:client &
        wait
        ;;
    *)
        echo Usage: $0 '<test id>' '<data size>' '<backend>' >&2
        exit 1
        ;;
esac
