apiVersion: v1
kind: Pod
metadata:
  name: atlas
  namespace: atlas
spec:
  containers:
    - name: Atlas
      image: microbenchmarks
      env:
        - name: FOO
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: foo
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
