version: "3"
services:
  replica-0:
    image: microbenchmarks
    build:
      context: ../../../
      dockerfile: testing-grounds/microbenchmarks-async/Dockerfile
    ports:
      - "10000:10000"
    extra_hosts: # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    volumes:
      - ../rust/docker-config:/usr/app/config
      - ../rust/ca-root:/usr/app/ca-root
      - ./logs:/usr/app/logs
    env_file:
      - ../docker_env
    environment:
      ID: 0
      OWN_NODE__NODE_ID: 0
      OWN_NODE__IP: "replica-0"
      OWN_NODE__HOSTNAME: "srv-0"
      OWN_NODE__NODE_TYPE: "Replica"
      RUST_BACKTRACE: full
    restart: no
    networks:
      - atlas_network
  replica-1:
    image: microbenchmarks
    build:
      context: ../../../
      dockerfile: testing-grounds/microbenchmarks-async/Dockerfile
    ports:
      - "10001:10000"
    extra_hosts: # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    volumes:
      - ../rust/docker-config:/usr/app/config
      - ../rust/ca-root:/usr/app/ca-root
      - ./logs:/usr/app/logs
    env_file:
      - ../docker_env
    environment:
      ID: 1
      OWN_NODE__NODE_ID: 1
      OWN_NODE__IP: "replica-1"
      OWN_NODE__HOSTNAME: "srv-1"
      OWN_NODE__NODE_TYPE: "Replica"
      RUST_BACKTRACE: full
    restart: no
    networks:
      - atlas_network
  replica-2:
    image: microbenchmarks
    build:
      context: ../../../
      dockerfile: testing-grounds/microbenchmarks-async/Dockerfile
    ports:
      - "10002:10000"
    extra_hosts: # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    volumes:
      - ../rust/docker-config:/usr/app/config
      - ../rust/ca-root:/usr/app/ca-root
      - ./logs:/usr/app/logs
    env_file:
      - ../docker_env
    environment:
      ID: 2
      NODE_ID: 2
      OWN_NODE__NODE_ID: 2
      OWN_NODE__IP: "replica-2"
      OWN_NODE__HOSTNAME: "srv-2"
      OWN_NODE__NODE_TYPE: "Replica"
      RUST_BACKTRACE: full
    restart: no
    networks:
      - atlas_network
  replica-3:
    image: microbenchmarks
    build:
      context: ../../../
      dockerfile: testing-grounds/microbenchmarks-async/Dockerfile
    ports:
      - "10003:10000"
    extra_hosts: # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    volumes:
      - ../rust/docker-config:/usr/app/config
      - ../rust/ca-root:/usr/app/ca-root
      - ./logs:/usr/app/logs
    env_file:
      - ../docker_env
    environment:
      ID: 3
      NODE_ID: 3
      OWN_NODE__NODE_ID: 3
      OWN_NODE__IP: "replica-3"
      OWN_NODE__HOSTNAME: "srv-3"
      OWN_NODE__NODE_TYPE: "Replica"
      RUST_BACKTRACE: full
    restart: no
    networks:
      - atlas_network
  client-0:
    image: microbenchmarks
    build:
      context: ../../../
      dockerfile: testing-grounds/microbenchmarks-async/Dockerfile
    ports:
      - "10004:10000"
    extra_hosts: # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    volumes:
      - ../rust/docker-config:/usr/app/config
      - ../rust/ca-root:/usr/app/ca-root
      - ./logs:/usr/app/logs
    env_file:
      - ../docker_env
    environment:
      ID: 1000
      OWN_NODE__NODE_ID: 1000
      OWN_NODE__IP: "client-0"
      OWN_NODE__HOSTNAME: "cli-0"
      OWN_NODE__NODE_TYPE: "Client"
      CLIENT: 1
      RUST_BACKTRACE: full
    restart: no
    networks:
      - atlas_network
networks:
  atlas_network:
    driver: bridge