apiVersion: v1

kind: PersistentVolume
metadata:
  name: atlas-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/atlas-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlas-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/atlas-1
