#!/bin/sh

main() {
    # setup
    check_root
    update_max_fds
    import_env
    check_env

    # exec
    select_backend
}

die() {
    echo $@ >&2
    exit 1
}

check_root() {
    if [ $(id -u) -ne 0 ]; then
        die Error: This script needs to be run as root.
    fi
}

update_max_fds() {
    ulimit -n 65535 2>/dev/null
    if [ $? -ne 0 ]; then
        die Error: Failed to update max open file descriptors!
    fi
}

import_env() {
    . ./env 2>/dev/null || die Error: No environment file found: env
}

check_env() {
    _NEED_ENV="NUM_CLIENTS NUM_REPLICAS BATCH_SIZE ID LOCAL CLIENT \
        BACKEND OPS_NUMBER MEASUREMENT_INTERVAL STATE_SIZE REPLY_SIZE REQUEST_SIZE"

    for var in $_NEED_ENV; do
        if [ -z $(eval "echo \$$var") ]; then
            die Error: Variable is unset in environment file: $var
        fi
    done
}

select_backend() {
    cd $BACKEND 2>/dev/null || die Error: Invalid backend: $BACKEND
    exec ./run
}

main
