#!/bin/sh

main() {
    # setup
    import_env $@
    update_max_fds

    # exec
    select_backend
}

die() {
    echo $@ >&2
    exit 1
}

import_env() {
    . ./env 2>/dev/null || die Error: No environment file found: env
    case $1 in
        stop)
            # stop running replicas
            if [ -f $BACKEND/stop ]; then
                $BACKEND/stop
                exit 0
            else
                die Error: Invalid backend: $BACKEND
            fi
            ;;
        clients)
            export CLIENT=1
            ;;
        servers)
            export CLIENT=0
            ;;
        *)
            die Usage: $0 '<clients|servers|stop>'
    esac
    check_env
}

check_env() {
    _NEED_ENV="NUM_CLIENTS NUM_REPLICAS BATCH_SIZE ID LOCAL BACKEND VERBOSE \
        OPS_NUMBER MEASUREMENT_INTERVAL STATE_SIZE REPLY_SIZE REQUEST_SIZE \
        REQUEST_SLEEP_MILLIS UPDATE_MAX_FDS"

    for var in $_NEED_ENV; do
        if [ -z $(eval "echo \$$var") ]; then
            die Error: Variable is unset in environment file: $var
        fi
    done
}

update_max_fds() {
    if [ $UPDATE_MAX_FDS -eq 1 ]; then
        if [ $(id -u) -ne 0 ]; then
            die Error: This script needs to be run as root.
        fi

        ulimit -n 65535 2>/dev/null
        if [ $? -ne 0 ]; then
            die Error: Failed to update max open file descriptors!
        fi
    fi
}

select_backend() {
    cd $BACKEND 2>/dev/null || die Error: Invalid backend: $BACKEND
    exec ./run
}

main $@
