#!/bin/sh

# config params
REPLICAS="4 7 10 13"
BATCHES="8 16 32 128 512 1024"
CLIENTS="1 10 30 60 100 1000"
RESULTS=results

# header
for no_replicas in $(echo $REPLICAS); do
    for no_clients in $(echo $CLIENTS); do
        printf ",%d" $no_replicas
    done
done
printf "\n"
for no_replicas in $(echo $REPLICAS); do
    for no_clients in $(echo $CLIENTS); do
        printf ",%d" $no_clients
    done
done
printf "\n"

# data
for batch_size in $(echo $BATCHES); do
    for run_no in `seq 0 2`; do
        if [ $run_no -eq 0 ]; then
            printf "%d" $batch_size
        fi
        for no_replicas in $(echo $REPLICAS); do
            for no_clients in $(echo $CLIENTS); do
                targetdir="${RESULTS}/r=${no_replicas}/b=${batch_size}/c=${no_clients}/run=${run_no}"
                printf ",%.2f" `cat ${targetdir}/client_stdout | grep Throughput | cut -f3 -d, | tr -d ' '` 2>/dev/null
            done
        done
        printf "\n"
    done
done
