#!/bin/sh

# avoid accidentally terminating benchmarks
trap '' INT

# helper funs
log() {
    echo $(date +%s): $@ >&2
}

REPLICAS="4 7 10 13"
BATCHES="8 16 32 128 512 1024"
CLIENTS="1 10 30 60 100 1000"

mkdir -p results

for no_replicas in $(echo $REPLICAS); do
    for batch_size in $(echo $BATCHES); do
        for no_clients in $(echo $CLIENTS); do
            targetdir="results/r=${no_replicas}/b=${batch_size}/c=${no_clients}"
            start=${targetdir}/start

            mkdir -p $targetdir
            date +%s > $start

            log Benchmarking with params: r=$no_replicas b=$batch_size c=$no_clients

            # start replicas in cop0?
            for i in `seq 0 $(expr $no_replicas - 1)`; do
                ippart=$(expr $i % 4)
                cop=cop${ippart}
                ip=192.168.70.$(expr 16 + $ippart)

                log '>' Starting replica $i 'in' $cop "($ip)"

                #ssh $cop "cd tg; "
            done
        done
    done
done
