#!/bin/sh

generate_conf() {
    if [ $LOCAL -eq 1 ]; then
        ./generate_conf_local $@ || exit 1
    else
        ./generate_conf $@ || exit 1
    fi

    if [ ! -f config/clients.config ]; then
        echo Error: Missing config/clients.config! >&2
        exit 1
    fi

    if [ ! -f config/replicas.config ]; then
        echo Error: Missing config/replicas.config! >&2
        exit 1
    fi

    if [ ! -f config/batch.config ]; then
        echo Error: Missing config/batch.config! >&2
        exit 1
    fi
}

exec_microbenchmarks() {
    exec env RUSTFLAGS="-C target-cpu=native" cargo run --release
}

generate_conf $NUM_CLIENTS $NUM_REPLICAS $BATCH_SIZE
exec_microbenchmarks
