#!/usr/bin/env python3

def main():
    with open('/tmp/consensus/input', 'w') as f:
        while True:
            try:
                line = input('Request> ')
                f.write(line)
                f.write('\n')
                f.flush()
            except (EOFError, KeyboardInterrupt):
                print()
                return

if __name__ == '__main__':
    main()
