#!/bin/sh

PASS=123456

CA_ROOT=ca-root
KEYSTORE=$CA_ROOT/keystore.jks
TRUSTSTORE=$CA_ROOT/truststore.jks

SERVICE_CA=service/$CA_ROOT
CLI_PREFIX=cli

updatecwd() {
    cd "$(dirname $0)"
}

regenerateca() {
    ./service/ca
}

regenerate() {
    echo Removing old Java CA
    rm -rf $CA_ROOT
    mkdir $CA_ROOT

    regenerateca

    echo Generating new Java TrustStore
    yes | keytool -keystore $TRUSTSTORE -import -file $SERVICE_CA/crt -storepass $PASS

    for cli in $(find $SERVICE_CA -name "${CLI_PREFIX}*" -type d); do
        target=$(basename $cli)
        echo Generating PKCS12 KeyStore for $target
        openssl pkcs12 -export \
            -in $cli/crt -inkey $cli/key -CAfile $SERVICE_CA/crt \
            -password 'pass:' -out $CA_ROOT/${target}.pfx
    done
}

main() {
    updatecwd
    regenerate
}

main
