#!/bin/sh

check_args() {
    if [ $# -lt 4 ]; then
        echo Usage: $0 '<num-clients>' '<num-replicas>' '<batch-size>' >&2
        exit 1
    fi
}

load_conf() {
    if [ -f config/generate ]; then
        ./config/generate $@ || exit 1
    else
        echo Error: Config generating script is absent! >&2
        exit 1
    fi

    . ./config/run.config

    DB=febft.ycsb.YCSBClient
    JAR=build/libs/febft-ycsb-all.jar
    WORKLOAD=config/workload.config
}

build_jar() {
    stat $JAR 2>/dev/null
    if [ $? -ne 0 ]; then
        ./gradlew shadowJar
    fi
}

ycsb_main() {
    ${YCSB_HOME}/bin/ycsb run $DB -cp $JAR -P $WORKLOAD -threads ${CLIENTS:-1}
}

check_args $@
load_conf $@
build_jar
ycsb_main
