#!/bin/sh

update_max_fds() {
    ulimit -n 65535 2>/dev/null
    if [ $? -ne 0 ]; then
        echo Error: Failed to update max open file descriptors! >&2
        exit 1
    fi
}

check_args() {
    if [ $# -lt 3 ]; then
        echo Usage: $0 '<num-clients>' '<num-replicas>' '<batch-size>' >&2
        exit 1
    fi
}

load_conf() {
    if [ -f config/generate ]; then
        cd config
        ./generate $@ || exit 1

        stat clients.config 2>/dev/null
        if [ $? -ne 0 ]; then
            echo Error: Missing config/clients.config! >&2
            exit 1
        fi

        stat replicas.config 2>/dev/null
        if [ $? -ne 0 ]; then
            echo Error: Missing config/replicas.config! >&2
            exit 1
        fi

        stat batch.config 2>/dev/null
        if [ $? -ne 0 ]; then
            echo Error: Missing config/batch.config! >&2
            exit 1
        fi

        . ./run.config
        cd ..
    else
        echo Error: Config generating script is absent! >&2
        exit 1
    fi

    DB=febft.ycsb.YCSBClient
    JAR=build/libs/febft-ycsb-all.jar
    WORKLOAD=config/workload.config
}

build_jar() {
    stat $JAR 2>/dev/null
    if [ $? -ne 0 ]; then
        ./gradlew shadowJar
    fi
}

ycsb_main() {
    ${YCSB_HOME}/bin/ycsb run $DB -cp $JAR -P $WORKLOAD -threads ${CLIENTS:-1}
}

update_max_fds
check_args $@
load_conf $@
build_jar
ycsb_main
