bootstrap_nodes = [
    { node_id = 0, ip = "10.0.0.7", port = 10000, hostname = "srv0", node_type = "Replica" },
    { node_id = 1, ip = "10.0.0.8", port = 10000, hostname = "srv1", node_type = "Replica" },
    { node_id = 2, ip = "10.0.0.9", port = 10000, hostname = "srv2", node_type = "Replica" },
    { node_id = 3, ip = "10.0.0.10", port = 10000, hostname = "srv3", node_type = "Replica" },
]

[own_node]
#node_id = 0
#ip = ""
port = 10000
#hostname = "srv0"
#node_type = "Replica"
