#!/bin/sh

gradle_wrapper() {
    if [ -n "$JAVA_HOME" ]; then
        ./gradlew -Dorg.gradle.java.home=$JAVA_HOME $@
    else
        ./gradlew $@
    fi
}

gradle_wrapper shadowJar
retcode=$?
gradle_wrapper --stop
exit $retcode
