#!/bin/sh

main() {
    compile
    [ $CLIENT -eq 1 ] && clients_main || servers_main
}

compile() {
    [ $COMPILE -eq 1 ] && ./compile
}

servers_main() {
    [ $LOCAL -eq 1 ] && servers_local_main || servers_cop_main
}

servers_local_main() {
    ./generate_conf_local
    for ID in `seq 0 $(expr $NUM_REPLICAS - 1)`; do
        start_replica $ID &
        sleep 0.5
    done
    wait
}

servers_cop_main() {
    ./generate_conf_cop
    exec start_replica $ID
}

clients_main() {
    [ $LOCAL -eq 1 ] && ./generate_conf_local || ./generate_conf_cop
    start_clients
}

start_replica() {
    exec java -jar build/libs/bft-smart-all.jar server \
        $1 $MEASUREMENT_INTERVAL $REPLY_SIZE $STATE_SIZE $VERBOSE nosig ''
}

start_clients() {
    exec java -jar build/libs/bft-smart-all.jar client \
        1000 $NUM_CLIENTS $OPS_NUMBER $REQUEST_SIZE $REQUEST_SLEEP_MILLIS \
        false $VERBOSE nosig
}

main
