#!/bin/sh

#ThroughputLatencyClient <initial client id> <number of clients> <number of operations> <request size> <interval (ms)> <read only?> <verbose?> <nosig | default | ecdsa>

#ThroughputLatencyServer <processId> <measurement interval> <reply size> <state size> <context?> <nosig | default | ecdsa> [rwd | rw]

main() {
    [ $CLIENT -eq 1 ] && clients_main || servers_main
}

servers_main() {
    [ $LOCAL -eq 1 ] && servers_local_main || servers_cop_main
}

servers_local_main() {
    ./generate_conf_local

    for ID in `seq 0 $(expr $NUM_REPLICAS - 1)`; do
        start_replica $ID &
    done

    wait
}

servers_cop_main() {
    ./generate_conf_cop

    exec java -jar build/libs/bft-smart-all.jar server $ID $MEASUREMENT_INTERVAL $REPLY_SIZE $STATE_SIZE $VERBOSE nosig ''
}

clients_main() {
    [ $LOCAL -eq 1 ] && clients_local_main || clients_cop_main
}

clients_local_main() {
    true
}

clients_cop_main() {
    true
}

start_replica() {
    java -jar build/libs/bft-smart-all.jar server $ID $MEASUREMENT_INTERVAL $REPLY_SIZE $STATE_SIZE $VERBOSE nosig '' &
}
