replicas:
  hosts:
    theia221:
      ansible_host: theia221
      ansible_user: nneto
      node_id: 0
      machine_ip: theia221.dcc.fc.up.pt
    theia222:
      ansible_host: theia222
      ansible_user: nneto
      node_id: 1
      machine_ip: theia222.dcc.fc.up.pt
    theia223:
      ansible_host: theia223
      ansible_user: nneto
      node_id: 2
      machine_ip: theia223.dcc.fc.up.pt
    theia224:
      ansible_host: theia224
      ansible_user: nneto
      node_id: 3
      machine_ip: theia224.dcc.fc.up.pt
clients:
  hosts:
    theia225:
      ansible_host: theia225
      ansible_user: nneto
      node_id:
        - 1000
        - 1003
      machine_ip: theia225.dcc.fc.up.pt
    theia226:
      ansible_host: theia226
      ansible_user: nneto
      node_id:
        - 1001
        - 1004
      machine_ip: theia226.dcc.fc.up.pt
    theia227:
      ansible_host: theia227
      ansible_user: nneto
      node_id:
        - 1002
        - 1005
      machine_ip: theia227.dcc.fc.up.pt