replicas:
  hosts:
    theia221:
      ansible_host: theia221
      ansible_user: nneto
      node_id: 0
      machine_ip: theia221.dcc.fc.up.pt
    theia222:
      ansible_host: theia222
      ansible_user: nneto
      node_id: 1
      machine_ip: theia222.dcc.fc.up.pt
    theia223:
      ansible_host: theia223
      ansible_user: nneto
      node_id: 2
      machine_ip: theia223.dcc.fc.up.pt
    theia224:
      ansible_host: theia224
      ansible_user: nneto
      node_id: 3
      machine_ip: theia224.dcc.fc.up.pt
clients:
  hosts:
    theia225:
      ansible_host: theia225
      ansible_user: nneto
      node_id:
        - 1000
      machine_ip: theia225.dcc.fc.up.pt
    theia226:
      ansible_host: theia226
      ansible_user: nneto
      node_id:
        - 1011
      machine_ip: theia226.dcc.fc.up.pt
    theia227:
      ansible_host: theia227
      ansible_user: nneto
      node_id:
        - 1021
      machine_ip: theia227.dcc.fc.up.pt
    minion1:
      ansible_host: minion1
      ansible_user: nneto
      node_id:
        - 1031
      machine_ip: 192.168.70.168
    minion2:
      ansible_host: minion2
      ansible_user: nneto
      node_id:
        - 1041
      machine_ip: 192.168.70.169
    minion3:
      ansible_host: minion3
      ansible_user: nneto
      node_id:
        - 1051
      machine_ip: 192.168.70.170
    minion4:
      ansible_host: minion4
      ansible_user: nneto
      node_id:
        - 1061
      machine_ip: 192.168.70.171
    minion5:
      ansible_host: minion5
      ansible_user: nneto
      node_id:
        - 1071
      machine_ip: 192.168.70.172
    minion6:
      ansible_host: minion6
      ansible_user: nneto
      node_id:
        - 1081
      machine_ip: 192.168.70.173
    minion7:
      ansible_host: minion7
      ansible_user: nneto
      node_id:
        - 1091
      machine_ip: 192.168.70.174
    minion8:
      ansible_host: minion8
      ansible_user: nneto
      node_id:
        - 1101
      machine_ip: 192.168.70.175