- hosts: all
  name: Setup environment
  gather_facts: no
  vars:
    bin_file: "microbenchmarks"
    ca_root_zip_file: "ca-root.zip"
    invidual_env_files: "individual-envs"
    working_dir: "/home/{{ansible_user}}/atlas-microbenchmarks-bare-metal"
  tasks:
    - name: Clear current state
      file:
        path: "{{ working_dir }}"
        state: absent
    - name: Create working directory
      file:
        path: "{{ working_dir }}"
        state: directory
        mode: '0755'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
    - name: Copy the executable
      copy:
        src: "{{bin_file}}"
        dest: "{{working_dir}}/{{bin_file}}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    - name: Copy the ca-root
      copy:
        src: "{{ca_root_zip_file}}"
        dest: "{{working_dir}}/ca-root.zip"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    - name: Unzip the ca-root
      shell: unzip {{ca_root_zip_file}}
      args:
        chdir: "{{working_dir}}"
    - name: Copy the env file
      copy:
        src: ".env"
        dest: "{{working_dir}}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    - name: Copy the start script
      copy:
        src: "run.sh"
        dest: "{{working_dir}}/run.sh"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

